#!/bin/python3
 #EJERCICIO1
import math
import os
import random
import re
import sys



n = 'Ingresa un numero entero'
n = int(input().strip())
if n % 2 != 0:
    print(" Weird")
elif (n % 2) == 0 and n >= 2 and n <= 5 :
    print("Not Weird") 
elif (n % 2) == 0 and n >= 6 and n <= 10 :
    print("Weird")
elif n % 2 == 0 and n > 20 :
    print("Not Weird") 


